### ISSUE TITLE
Delete Operation on MacOs

### ISSUE THREAD

**Issue by naser-kazemi** [Arash1381-y/fsmNinja#3]
Hi, Thanks for your contribution to the project. The GUI is much smoother. I also like the right-side panel showing the different properties of each state.

There is still a problem with the deleting functionality for both states and links. I have tested it on Google Chrome, Safari, and Firefox on Mac OS. The problem is present in all of these browsers. 

There is also another issue. The text fields do not accept Persian text. But I can enter the text manually in the "name" property using the right-side panel. It's not a big deal but it would be great if you fix this one too.

**Comment by Ehsan200** [comment]
Hello there.
Use `fn + backspace`.

**Comment by naser-kazemi** [comment]
> Hello there. Use `fn + backspace`.

Hi.
Thank you. Then the problem is solved.
